on:
  push:
    branches: master

name: Create-pkgdown-site

jobs:
  pkgdown:
    runs-on: macOS-latest

    env:
      # for remotes::install_github
      GITHUB_PAT: ${{ secrets.GHPAT }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript {0}
